on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: docker
    steps:
      - uses: actions/checkout@v4

      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - run: bun install
      - run: bun run build.ts

      - uses: actions/deploy-pages@main
        with:
          folder: dist
